[ BB2-1117 ] fhir endpoints
CMSgov/cms-bb2-python-sdk pull request #1
Opened 2022-02-21 20:42 UTC by nbragdon

2022-03-11 15:35 UTC, dtisza1 requested changes
@nbragdon This is looking great!

Just some naming related changes and questions about the retry timings.

2022-03-11 15:35 UTC, dtisza1 commented on src/fhirRequest.py
> +        total=3, backoff_factor=0.2, status_forcelist=[500, 502, 503, 504]
I think we should add 429 here for "rate limit exceeded".

The backoff_factor seems low?  Especially for the back end related errors that are resource related and might take a little time for a repeat call to be successful.  

Found these examples of retry timing per backoff_factor:

1 second the successive sleeps will be 0.5, 1, 2, 4, 8, 16, 32, 64, 128, 256.
2 seconds - 1, 2, 4, 8, 16, 32, 64, 128, 256, 512
10 seconds - 5, 10, 20, 40, 80, 160, 320, 640, 1280, 2560

Thinking maybe 5 or 10 might be a better value with 3x retries.

2022-03-18 20:12 UTC, dtisza1 approved these changes
This looks good to me!

Changes look good!

2022-03-18 20:27 UTC, JFU-GIT approved these changes
Looks good to me.

2022-03-21 19:15 UTC, merged